### ISSUE TITLE
Feature: Translator TTS? 

### ISSUE THREAD

**Issue by SchoolyB** [SchoolyB/International-Data-Matrix#123]
A good feature to implement to the IDM would be text to speech for output translations on the translator page. A possible free solution might be using the (
[TTS Free](https://ttsfree.com/blog/developers-apis-documents.html) API

**Comment by SchoolyB** [comment]
Took about 10 attempts to make the format work how I wanted it to.

**Comment by SchoolyB** [comment]
Possible to implement TTS after rebuild

**Comment by SchoolyB** [comment]
started the [tts](https://github.com/SchoolyB/International-Data-Matrix/tree/tts) branch to begin tts builds. Decided it be best not use a 3rd party API.

**Comment by jimbo2150** [comment]
There's a TTS API built into browsers, I would use that. It's free since it's built into the browser.

[Web Speech API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Speech_API/Using_the_Web_Speech_API)

**Comment by SchoolyB** [comment]
Also looking into other input languages

**Comment by SchoolyB** [comment]
test
