### ISSUE TITLE
Feature: Loading screen  

### ISSUE THREAD

**Issue by SchoolyB** [SchoolyB/International-Data-Matrix#169]
Add a loading screen/wheel when loading country selection pages

**Comment by jimbo2150** [comment]
I am not seeing it take a long time. The images take a while but the page loads very fast. Where are you seeing the issue?

**Comment by SchoolyB** [comment]
@jimbo2150 Thats what I was referring to. The images take so long to load. So A loading bar or screen wouldn't be a good idea?

**Comment by jimbo2150** [comment]
Not for the images. In fact, I would add lazy loading onto the images so that only those that are close enough to the viewport load. If the user never scrolls down, those further down the list would never be loaded or need to be. Saves on bandwidth and reduces the users' CPU and memory usage.

**Comment by jimbo2150** [comment]
Note that periodically the loading will fail or take a upwards of 1-2 minutes to load the JSON file. It doesn't appear to be a software issue, likely a server issue. Not sure if this can be fixed. It is also making 2 requests for the countries JSON data. The first one always fails with a 404 and the second one succeeds. Not sure why this is being done twice. Maybe a separate issue?

**Comment by SchoolyB** [comment]
I can look into the failure. Never noticed it before. Perhaps some server side code.

**Comment by SchoolyB** [comment]
@jimbo2150 Found out why the API was always making a second call. It is because in [main.tsx](https://github.com/SchoolyB/International-Data-Matrix/blob/master/client/src/main.tsx) I had `React.StrictMode` enabled

**Comment by jimbo2150** [comment]
Nice.

Unfortunately the lazy loading doesn't work. I forgot the images are being added dynamically and apparently the lazy attribute doesn't work in that case. It still just loads all the images immediately.

**Comment by SchoolyB** [comment]
After getting a better understanding of render.com and the instance hibernation I am closing this issue
