### ISSUE TITLE
add maps for each country

### ISSUE THREAD

**Issue by SchoolyB** [SchoolyB/International-Data-Matrix#191]

**Comment by SchoolyB** [comment]
Add a map for each country to the project to be generated through the [id].tsx page. Source: https://www.worldometers.info/maps/

**Comment by SchoolyB** [comment]
Added A-B in 752a4120b0b89d06b9b1a6d7fc27e0991246f06c

**Comment by SchoolyB** [comment]
https://github.com/SchoolyB/International-Data-Matrix/issues/186#issuecomment-1537671254

**Comment by jimbo2150** [comment]
Another option would be to embed a Google map into the page.

**Comment by SchoolyB** [comment]
@jimbo2150 I'm considering doing this. I can pass `{state.lat} ` & `{state.lon}`  in the `[id].tsx` file into the object in this snippet from the Google Maps API which will then load a map that is focused in on the latitude and longitude of the capitol of the current country the user happens to be on. 

`const map = () => {
	const { isLoaded } = useLoadScript({
		googleMapsApiKey: API_KEY || '',
	})
	const center = useMemo(() => ({ lat: 0, lng: 0 }), [])
 
`

**Comment by SchoolyB** [comment]
Add D-H in #211

**Comment by SchoolyB** [comment]
Add I - Z in #212
