### ISSUE TITLE
Add link to map page in nav menu and footer

### ISSUE THREAD

**Issue by SchoolyB** [SchoolyB/International-Data-Matrix#224]
Add a link to https://international-data-matrix.vercel.app/map into the footer and header nav menu

**Comment by DrSwaggos** [comment]
Brief question: Is it normal, that Header component cannot be compiled because it cannot find rsuite home icon?

**Comment by SchoolyB** [comment]
@DrSwaggos that's interesting. I have never had that issue so im a bit unsure.

 @m-oniqu3 have you dealt with something like this before?

**Comment by DrSwaggos** [comment]
@SchoolyB would you be so kind and take a look at my changes. I introduced the links to the map page on both the footer and the header but, as I mentioned before, I had this issue with rsuite icons.

**Comment by SchoolyB** [comment]
@DrSwaggos I'm already looking at it 😄. LGTM! Feel free to make a PR to the `Development` branch

**Comment by SchoolyB** [comment]
@DrSwaggos Nicely done! 😄
