### ISSUE TITLE
Feature: nav menu closes when user clicks outside of it

### ISSUE THREAD

**Issue by SchoolyB** [SchoolyB/International-Data-Matrix#241]
Currently the only way to close the nav menu is to click on the menu icon again. I think having the option to just click outside of the menu and it closing would be beneficial

**Comment by Elleriyc** [comment]
Hello, i'm a student in computer science and i looking for my first contribution for a class can I take this one ?

**Comment by SchoolyB** [comment]
@Elleriyc Sure!!! Please see https://github.com/SchoolyB/International-Data-Matrix/blob/master/CONTRIBUTING.md

**Comment by Elleriyc** [comment]
Thanks you, i'm gonna work on it !
