### ISSUE TITLE
Feature: Replace loading text with loading bar or svg

### ISSUE THREAD

**Issue by m-oniqu3** [SchoolyB/International-Data-Matrix#245]

**Comment by SchoolyB** [comment]
@m-oniqu3 👀I'm liking the idea

**Comment by MichealPearce** [comment]
https://loading.io/css/
https://projects.lukehaas.me/css-loaders/
https://cssloaders.github.io/

**Comment by SchoolyB** [comment]
@MichealPearce Funny seeing you round these parts

**Comment by MichealPearce** [comment]
@SchoolyB discord notifications work like a charm

**Comment by SchoolyB** [comment]
@MichealPearce Do you think the cssloaders that you mentioned would work for #169?

**Comment by MichealPearce** [comment]
@SchoolyB yea that's what I would use for a loading screen
